version: '3'
services:
  webapp:
    build:
      context: ./webapp #Nome Temporaneo
    ports:
      - 3500:3500
    depends_on:
      - supabase
  supabase:
    build:
      context: ./supabase
    ports:
      - 5432:5432
  nginx:
    build:
      context: ./nginx
    ports:
      - 8500:8500
    depends_on:
      - webapp #Nome Temporaneo
