# pull Immagine node in Alpine
FROM node:13.4.12-alpine

# directory di lavoro
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# Copia intera app nel container
COPY . ./

# avvia app
CMD ["npm", "start"]